export enum TechnologyName {
	CSS = "CSS",
	DIGITAL_OCEAN = "Digital Ocean",
	DOCKER = "Docker",
	ELECTRON = "Electron",
	GITHUB = "GitHub",
	JAVASCRIPT = "JavaScript",
	NESTJS = "NestJS",
	NEXTJS = "Next.js",
	NGINX = "Nginx",
	NODE_JS = "Node.js",
	OPENAI = "OpenAI",
	POSTGRESQL = "PostgreSQL",
	PRISMA = "Prisma",
	PYTHON = "Python",
	REACT = "React",
	REDUX = "Redux",
	SASS = "SASS",
	SQL = "SQL",
	STRIPE = "Stripe",
	TAILWIND_CSS = "Tailwind CSS",
	TANSTACK_QUERY = "Tanstack Query",
	TYPESCRIPT = "TypeScript",
	VSCODE = "Visual Studio Code",
	WEBPACK = "Webpack",
	ZUSTAND = "Zustand",
}

export const technologies = [
	{ name: TechnologyName.CSS, iconPath: "/assets/images/tech/css.png" },
	{
		name: TechnologyName.DIGITAL_OCEAN,
		iconPath: "/assets/images/tech/digitalocean.png",
	},
	{ name: TechnologyName.DOCKER, iconPath: "/assets/images/tech/docker.png" },
	{
		name: TechnologyName.ELECTRON,
		iconPath: "/assets/images/tech/electron.png",
	},
	{ name: TechnologyName.GITHUB, iconPath: "/assets/images/tech/github.png" },
	{ name: TechnologyName.JAVASCRIPT, iconPath: "/assets/images/tech/js.png" },
	{ name: TechnologyName.NESTJS, iconPath: "/assets/images/tech/nestjs.png" },
	{ name: TechnologyName.NEXTJS, iconPath: "/assets/images/tech/nextjs.png" },
	{ name: TechnologyName.NGINX, iconPath: "/assets/images/tech/nginx.png" },
	{ name: TechnologyName.NODE_JS, iconPath: "/assets/images/tech/nodejs.png" },
	{ name: TechnologyName.OPENAI, iconPath: "/assets/images/tech/openai.png" },
	{
		name: TechnologyName.POSTGRESQL,
		iconPath: "/assets/images/tech/postgres.png",
	},
	{ name: TechnologyName.PRISMA, iconPath: "/assets/images/tech/prisma.png" },
	{ name: TechnologyName.PYTHON, iconPath: "/assets/images/tech/python.png" },
	{ name: TechnologyName.REACT, iconPath: "/assets/images/tech/react.png" },
	{ name: TechnologyName.REDUX, iconPath: "/assets/images/tech/redux.png" },
	{ name: TechnologyName.SASS, iconPath: "/assets/images/tech/sass.png" },
	{ name: TechnologyName.SQL, iconPath: "/assets/images/tech/sql.png" },
	{ name: TechnologyName.STRIPE, iconPath: "/assets/images/tech/stripe.png" },
	{
		name: TechnologyName.TAILWIND_CSS,
		iconPath: "/assets/images/tech/tailwind.png",
	},
	{
		name: TechnologyName.TANSTACK_QUERY,
		iconPath: "/assets/images/tech/tanstack.png",
	},
	{ name: TechnologyName.TYPESCRIPT, iconPath: "/assets/images/tech/ts.png" },
	{ name: TechnologyName.VSCODE, iconPath: "/assets/images/tech/vsc.png" },
	{ name: TechnologyName.WEBPACK, iconPath: "/assets/images/tech/webpack.png" },
	{ name: TechnologyName.ZUSTAND, iconPath: "/assets/images/tech/zustand.png" },
];
